if there is an error in the shape match while loss calculation, modify the variable "shape_img" in DataModule.py in Dataset folder to match it
with the output. They must have the same shape.